"""Create a baseline migrations

Revision ID: 3e80bacefc53
Revises: dfc4f833a755
Create Date: 2024-03-21 23:49:52.055274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e80bacefc53'
down_revision: Union[str, None] = 'dfc4f833a755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=150), nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=150), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=150), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
