"""Create a baseline migrations

Revision ID: f3d13664a257
Revises: ff5a30c4ffa0
Create Date: 2024-03-21 17:54:21.269737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d13664a257'
down_revision: Union[str, None] = 'ff5a30c4ffa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
